---
apiVersion: v1
kind: Service
metadata:
  name: super-service
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    -port: 80
    targetPort: 3000
  type: LoadBalancer
---
spec:
  replicas: 2
  appLabel: pod-info
